language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn docs:build
deploy:
  provider: pages
  cleanup: false
  overwrite: true
  local_dir: docs/.vuepress/dist
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master